---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: my-secret
  namespace: default
spec:
  encryptedData:
    secret1: AgAl5yUL6CX5ACvSLC/Vf2BZSzYxxBcXVNYzvY9wGUtitTF08iumPGF/hhqIhJ7pzwmlSpk+iwVlmRT9UQZZrrjywM2/HhzN/1ljuBHRGVL6murQlvMXDveF/FlECTZIdDLF+OqmqihYagWH95QeOcbP9wyrPnZzNiVUSLyKQcu2MvLKUcmxgNimMB8+ljjClXL9MmJ7/9hZHFEVOXvOWlBp4C5ytOzBvLchUwONrmvlVhL1FOxRLpE4/EiDSVxkZoQWeFkV2A12P25qry9eLX5B7ZRFQMey/FeBJX0V0BH4W6899W6vMSKkF5eZ264xxRLMzqMxmZLCP5iCBGSddU2o7tcG1jSsx+5kcE6AAg7dstO4/q9Z9J6GOYmJTXUpMbDO/6x3bQiDn/+uEK93vZZHN+V/1r1gwVOXoCUQ8Y9xsxnOUx66JSljcC/ozv39h7Ynw3+FDjXDzBLLelkhfiY2YAMayp3iWifm6mR3Pa8Pux87EgDhcE5rSdxqvT+Lw8ga9EnmmZE9i9FeO9GwLBsnicw0LtwH7Swjfc+dS71Uui90VOirGVXnQbwfh/PN/ZpwVJwTprQ4FS3j1NPr4MvPdEpM50sXsQJNoZJ/kkcjOxGlb7YKE4qvns90egCEK2azcZsvjTZeIlb2GV3MTkTQBfjZwbkv+boRkdonkTcso7Tyd1ceavZxfz29/XK65cyXCSpf4oc=
    secret2: AgAo5KXOcC/lD5bQIGW55SU9kdEe10CmNpyBe1DgK8xCVIX9DayQ/yXmy5vyYGeHBnWRXcw7V/QlkXWj5zoBPtNOAwTjEcAyk7B4rl52ItAqtLhVd+1XjGI3QWCPzT4MboyCyGvdXJUyvpyjVSshlLWHdMvpi4n3pMVDRI9jC17fHQLAdqof/43Uu70S+xQbowHrXnWkf1pG7zfoIbNMngfk1WFt9pWd3SUtAVq8vKWcaHsClih57d7pMoD5vSUM+N+buqhhi07G+kgweLaoCcrGblqSCkjTS5OsWIS04skc1VH5X3Qp1/mEDY61Wnx6caMB+NDr3UwwUirwmFKj52oldtrNxP4dXErESLSUEt9GlcF9MbLPOPkw8hR7c621v8eSzfNrNwM4yDWFIXM3M2DeK8hrfesW/5k+kDaYstf/qt5zq5eUf38mUOlGrJXEhzKwao5DFZpKD/gWfC+wUz0rEVYGvmJjDRl1hobuIrQ+lq09AzLy5/VuzoZOStmk5vxsFpR575MbbyxJmD9coU/XEc1sKSDozkGFyqzZAWjGoiB22fm/pSb1WqZJLQNxuMKDzsYW2s9v1vHaAGbPnmrOfaT5Ak93UHib0/eIuZrzXnLpFWU9Yt/haTWLiBt9XhOzg8d1X7djYDAZAEmnjbSPPFgkYjp5vDL1HrUDZYe6VWsYzXKho+ZjnHP4S9g7qnv8c0Buow==
  template:
    metadata:
      creationTimestamp: null
      name: my-secret
      namespace: default
